import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { drizzle as drizzlePg } from 'drizzle-orm/node-postgres';
import { migrate as migratePg } from 'drizzle-orm/node-postgres/migrator';
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core';
import { drizzle as drizzlePglite } from 'drizzle-orm/pglite';
import { migrate as migratePglite } from 'drizzle-orm/pglite/migrator';
import pg from 'pg';
import * as schema from './schema';

export type Database = PgDatabase<PgQueryResultHKT, typeof schema>;
export type Transaction = Parameters<Parameters<Database['transaction']>[0]>[0];

export interface DatabaseConnection {
  db: Database;
  migrate: () => Promise<void>;
  close: () => Promise<void>;
}

/** SQL migrations generated by drizzle-kit. Scripts and tests run from the API package root. */
const MIGRATIONS_FOLDER = path.resolve(process.cwd(), 'drizzle');

const PGLITE_PREFIX = 'pglite:';

/**
 * `postgres://…` connects to a PostgreSQL server. `pglite:memory` or `pglite:<directory>` runs an
 * embedded PostgreSQL build instead: the same engine, used for tests and for development without
 * Docker.
 */
export function createDatabase(url: string): DatabaseConnection {
  if (url.startsWith(PGLITE_PREFIX)) {
    const location = url.slice(PGLITE_PREFIX.length);
    if (location !== 'memory') {
      mkdirSync(location, { recursive: true });
    }
    const client = location === 'memory' ? new PGlite() : new PGlite(location);
    const db = drizzlePglite({ client, schema, casing: 'snake_case' });
    return {
      db,
      migrate: () => migratePglite(db, { migrationsFolder: MIGRATIONS_FOLDER }),
      close: () => client.close(),
    };
  }

  const pool = new pg.Pool({ connectionString: url, max: 10 });
  const db = drizzlePg({ client: pool, schema, casing: 'snake_case' });
  return {
    db,
    migrate: () => migratePg(db, { migrationsFolder: MIGRATIONS_FOLDER }),
    close: () => pool.end(),
  };
}
