import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Where uploaded bytes live. The database row decides who may read a file; the storage only keeps
 * bytes under an opaque key. A cloud bucket (S3-compatible, such as Cloudflare R2) can replace the
 * disk without touching the rest of the API.
 */
export interface FileStorage {
  put(key: string, data: Buffer): Promise<void>;
  /** Null when there is nothing under the key. */
  read(key: string): Promise<Buffer | null>;
  remove(key: string): Promise<void>;
}

/** Keys are generated by the API (a UUID and an extension), never taken from a request. */
const SAFE_KEY = /^[0-9a-f-]{36}\.[a-z0-9]{2,5}$/;

function assertSafeKey(key: string): void {
  if (!SAFE_KEY.test(key)) {
    throw new Error(`Refusing unexpected storage key: ${key}`);
  }
}

export class DiskStorage implements FileStorage {
  constructor(private readonly root: string) {}

  private pathOf(key: string): string {
    assertSafeKey(key);
    // Two levels of folders from the key, so no folder holds too many files.
    return path.join(this.root, key.slice(0, 2), key.slice(2, 4), key);
  }

  async put(key: string, data: Buffer): Promise<void> {
    const target = this.pathOf(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, data, { flag: 'wx' });
  }

  async read(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.pathOf(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return null;
      }
      throw error;
    }
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }
}

export class MemoryStorage implements FileStorage {
  readonly files = new Map<string, Buffer>();

  put(key: string, data: Buffer): Promise<void> {
    assertSafeKey(key);
    this.files.set(key, data);
    return Promise.resolve();
  }

  read(key: string): Promise<Buffer | null> {
    return Promise.resolve(this.files.get(key) ?? null);
  }

  remove(key: string): Promise<void> {
    this.files.delete(key);
    return Promise.resolve();
  }
}
