import type { InterfaceLocale } from '../../i18n/config';

const ar = {
  title: 'نظام التصميم',
  intro:
    'المرجع البصري للمنصة: الألوان والخطوط والمكونات كما تظهر في الواجهة. كل مكون هنا يعمل بالعربية والإنجليزية ويدعم لوحة المفاتيح وقارئات الشاشة.',
  onThisPage: 'في هذه الصفحة',
  sections: {
    brand: 'العلامة',
    colors: 'الألوان',
    typography: 'الخطوط',
    buttons: 'الأزرار',
    forms: 'النماذج',
    display: 'عرض البيانات',
    feedback: 'التنبيهات والتقدم',
    navigation: 'التبويبات والنوافذ',
    media: 'الصوت',
  },
  brand: {
    body: 'شعار المنصة هو عدسة كلية اللغات والترجمة: ثماني شفرات تحمل حروفًا من لغات العالم حول الكرة الأرضية. عند الحركة تدور حلقة الشفرات وحدها والكرة ثابتة في المنتصف، شفرةً بعد شفرة مثل حلقة عدسة الكاميرا. محدد اللغة يستخدم عدسة من ست شفرات، واحدة لكل لغة في المنصة.',
    loading: 'مؤشر التحميل',
    hover: 'مرّر المؤشر فوق الشعار ليدور شفرة واحدة',
    selected: 'اللغة المختارة',
  },
  colors: {
    body: 'خلفية بيضاء، وأزرق مشتق من كحلي الجامعة للأفعال الأساسية، ولون مميز لكل مهارة. الأرقام بجانب كل زوج هي نسبة التباين محسوبة مباشرة من المتصفح.',
    primitives: 'الدرجات الأساسية',
    pairs: 'أزواج النص والخلفية',
    pass: 'يجتاز AA',
    fail: 'لا يجتاز',
  },
  typography: {
    body: 'Alexandria للعناوين، وIBM Plex Sans Arabic للنصوص، وNoto Sans للصينية واليابانية. كل الخطوط مستضافة داخل المنصة.',
    display: 'تعلّم لغة جديدة',
    heading: 'مستواك في القراءة: B1',
    paragraph:
      'اقرأ النص التالي ثم أجب عن الأسئلة. يمكنك الضغط على أي كلمة لمعرفة معناها ونطقها وإضافتها إلى قائمة كلماتك.',
  },
  buttons: {
    primary: 'ابدأ الاختبار',
    secondary: 'احفظ كمسودة',
    ghost: 'عرض التفاصيل',
    danger: 'حذف الإجابة',
    loading: 'جارٍ الإرسال',
    disabled: 'غير متاح',
    link: 'رابط بشكل زر',
    sizes: 'المقاسات',
    states: 'الحالات',
  },
  forms: {
    name: 'الاسم الكامل',
    nameHint: 'كما تريد أن يظهر في شهادة تحديد المستوى',
    email: 'البريد الجامعي',
    emailError: 'اكتب بريدًا ينتهي بـ ‎@acu.edu.eg',
    bio: 'لماذا تتعلم هذه اللغة؟',
    language: 'اللغة التي تريد تعلّمها',
    choose: 'اختر لغة',
    disabled: 'حقل غير قابل للتعديل',
    terms: 'أوافق على شروط الاستخدام',
    reminders: 'ذكّرني بالتدريب اليومي',
    remindersHint: 'رسالة قصيرة على بريدك مرة واحدة في اليوم',
    goal: 'هدفك من التعلّم',
    goals: { study: 'الدراسة', work: 'العمل', travel: 'السفر' },
    goalsHint: { work: 'سنركّز على المراسلات والمقابلات' },
  },
  display: {
    badges: 'الشارات',
    levels: 'مستويات الإطار الأوروبي',
    level: 'المستوى {{level}}',
    skills: 'المهارات',
    cards: 'البطاقات',
    cardTitle: 'الوحدة الثالثة: السفر',
    cardBody: '6 دروس · 24 تمرينًا',
    badge: {
      neutral: 'مسودة',
      info: 'جديد',
      success: 'مكتمل',
      warning: 'قيد المراجعة',
      danger: 'فائت',
      achievement: 'شهادة',
    },
  },
  feedback: {
    alerts: 'الرسائل',
    info: 'يبدأ الاختبار التالي يوم الأحد الساعة العاشرة صباحًا.',
    success: 'تم حفظ إجاباتك. يمكنك المتابعة من حيث توقفت.',
    warning: 'تبقّى على انتهاء الوقت 5 دقائق.',
    danger: 'تعذّر إرسال الإجابة. تحقق من اتصالك ثم حاول مرة أخرى.',
    toasts: 'الإشعارات المؤقتة',
    showToast: 'أظهر إشعارًا',
    toastTitle: 'تم حفظ التقدّم',
    toastBody: 'أكملت درس «في المطار».',
    showErrorToast: 'أظهر إشعار خطأ',
    errorToastTitle: 'انقطع الاتصال',
    progress: 'شريط التقدم',
    progressOf: '{{value}} من {{max}}',
    loading: 'التحميل',
  },
  navigation: {
    tabsLabel: 'أقسام الدرس',
    tabs: {
      text: 'النص',
      vocabulary: 'المفردات',
      questions: 'الأسئلة',
    },
    tabBody: {
      text: 'محتوى تبويب النص. استخدم الأسهم للتنقل بين التبويبات.',
      vocabulary: 'محتوى تبويب المفردات.',
      questions: 'محتوى تبويب الأسئلة.',
    },
    openDialog: 'افتح نافذة تأكيد',
    dialogTitle: 'إنهاء الاختبار؟',
    dialogBody: 'لن تتمكن من تعديل إجاباتك بعد الإنهاء. ستظهر درجتك فورًا.',
    dialogConfirm: 'إنهاء وتسليم',
  },
  media: {
    player: 'مشغل الصوت',
    limited: 'مشغل بعدد مرات محدود (للاختبارات)',
    track: 'محادثة في محطة القطار',
    recorder: 'مسجل الصوت',
    recorderHint: 'يحتاج إذن الميكروفون. التسجيل يبقى على جهازك ولا يُرفع.',
  },
};

type Copy = typeof ar;

const en: Copy = {
  title: 'Design system',
  intro:
    'The visual reference for the platform: colours, type and components as they appear in the product. Every component here works in Arabic and English and supports keyboards and screen readers.',
  onThisPage: 'On this page',
  sections: {
    brand: 'Brand',
    colors: 'Colour',
    typography: 'Typography',
    buttons: 'Buttons',
    forms: 'Forms',
    display: 'Data display',
    feedback: 'Feedback and progress',
    navigation: 'Tabs and dialogs',
    media: 'Audio',
  },
  brand: {
    body: 'The platform mark is the Faculty of Languages and Translation aperture: eight blades carrying letters from the world’s scripts around a globe. In motion only the ring of blades turns while the globe stays still, clicking round blade by blade like a camera lens. The language picker uses a six-blade aperture, one blade per language on the platform.',
    loading: 'Loading indicator',
    hover: 'Hover over the mark to turn it by one blade',
    selected: 'Selected language',
  },
  colors: {
    body: 'A white background, a blue derived from the university navy for primary actions, and one colour per skill. The number next to each pair is its contrast ratio, computed live in the browser.',
    primitives: 'Palette',
    pairs: 'Text and background pairs',
    pass: 'Passes AA',
    fail: 'Fails',
  },
  typography: {
    body: 'Alexandria for headings, IBM Plex Sans Arabic for text and Noto Sans for Chinese and Japanese. All fonts are self-hosted.',
    display: 'Learn a new language',
    heading: 'Your reading level: B1',
    paragraph:
      'Read the text below, then answer the questions. Tap any word to see its meaning and pronunciation and to add it to your word list.',
  },
  buttons: {
    primary: 'Start the test',
    secondary: 'Save as draft',
    ghost: 'View details',
    danger: 'Delete answer',
    loading: 'Submitting',
    disabled: 'Not available',
    link: 'Link styled as a button',
    sizes: 'Sizes',
    states: 'States',
  },
  forms: {
    name: 'Full name',
    nameHint: 'As it should appear on your placement certificate',
    email: 'University email',
    emailError: 'Enter an address ending in @acu.edu.eg',
    bio: 'Why are you learning this language?',
    language: 'Language you want to learn',
    choose: 'Choose a language',
    disabled: 'Read-only field',
    terms: 'I agree to the terms of use',
    reminders: 'Remind me to practise every day',
    remindersHint: 'One short email a day',
    goal: 'Your learning goal',
    goals: { study: 'Study', work: 'Work', travel: 'Travel' },
    goalsHint: { work: 'We will focus on emails and interviews' },
  },
  display: {
    badges: 'Badges',
    levels: 'CEFR levels',
    level: 'Level {{level}}',
    skills: 'Skills',
    cards: 'Cards',
    cardTitle: 'Unit 3: Travel',
    cardBody: '6 lessons · 24 exercises',
    badge: {
      neutral: 'Draft',
      info: 'New',
      success: 'Completed',
      warning: 'In review',
      danger: 'Missed',
      achievement: 'Certificate',
    },
  },
  feedback: {
    alerts: 'Messages',
    info: 'The next exam starts on Sunday at 10:00.',
    success: 'Your answers are saved. You can continue where you left off.',
    warning: 'Five minutes left before time runs out.',
    danger: 'Your answer could not be sent. Check your connection and try again.',
    toasts: 'Toasts',
    showToast: 'Show a toast',
    toastTitle: 'Progress saved',
    toastBody: 'You finished the lesson “At the airport”.',
    showErrorToast: 'Show an error toast',
    errorToastTitle: 'Connection lost',
    progress: 'Progress bars',
    progressOf: '{{value}} of {{max}}',
    loading: 'Loading',
  },
  navigation: {
    tabsLabel: 'Lesson sections',
    tabs: {
      text: 'Text',
      vocabulary: 'Vocabulary',
      questions: 'Questions',
    },
    tabBody: {
      text: 'Text tab content. Use the arrow keys to move between tabs.',
      vocabulary: 'Vocabulary tab content.',
      questions: 'Questions tab content.',
    },
    openDialog: 'Open a confirmation dialog',
    dialogTitle: 'Finish the exam?',
    dialogBody:
      'You will not be able to change your answers afterwards. Your score appears straight away.',
    dialogConfirm: 'Finish and submit',
  },
  media: {
    player: 'Audio player',
    limited: 'Limited-play player (for tests)',
    track: 'A conversation at the train station',
    recorder: 'Voice recorder',
    recorderHint:
      'Needs microphone permission. The recording stays on your device and is not uploaded.',
  },
};

export const DESIGN_SYSTEM_COPY: Record<InterfaceLocale, Copy> = { ar, en };
